# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ranrinc.github.io
title: Richard Tirtadji Personal webpages
email: rtirtadji@gmail.com
author: Richard Tirtadji
description: > # "Richard Tirtadji Personal webpage. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 Richard Tirtadji. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/RichardTirtadji
  - title: github
    url: https://github.com/ranrinc
  - title: linkedin
    url: https://www.linkedin.com/in/richard-tirtadji/
